kubeslice/docs

- README.md
Fixes #9 
- Corrected spelling of 'documentation'.
- Added [docusaurus SSG](https://docusaurus.io/) as a pre-requisite.
- Updated the installation section to include clone and change directory instructions.
> Updated with clone and change directory instructions

- README.md
> Typos fixed in README.md

- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/getting-started-with-cloud-clusters.mdx
- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/installing-kubeslice/creating-a-slice.mdx
- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/installing-kubeslice/installing-the-kubeslice-controller.mdx
- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/installing-kubeslice/registering-the-worker-cluster.mdx
- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/prerequisites/preparing-the-cloud-clusters-for-registration.mdx
- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/prerequisites/prerequisites.mdx
- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/tutorials/deploying-the-bookinfo-application-on-an-intra-cluster-slice.mdx
- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/tutorials/deploying-the-bookinfo-application.mdx
- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/tutorials/deploying-the-iperf-application-on-an-intra-cluster-slice.mdx
- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/tutorials/deploying-the-iperf-application.mdx
Fixed broken hyper links in OSS docs.
> update broken links

- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/uninstalling-kubeslice/offboarding-namespaces.mdx
Updated the serviceexport command
> updated serviceexport command

- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/prerequisites/preparing-the-cloud-clusters-for-registration.mdx
- versioned_docs/version-0.2.0/getting-started-with-kind-clusters.mdx
Changed the name of the repo for pulling the KubeSlice repo 
Changed `charts` to `kubeslice`
> Changed the name of the repo in the command for pulling the KubeSlice repo

- package-lock.json
- versioned_docs/version-0.2.0/community.mdx
/assign @divya-mohan0209 
Please review and comment
Addressing Issue https://github.com/kubeslice/docs/issues/8
Signed-off-by: Aman Sarraf <amansarrafnit@gmail.com>
> added join links to community page 

- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/prerequisites/preparing-the-cloud-clusters-for-registration.mdx
- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/prerequisites/prerequisites.mdx
Added that AWS-EKS is supported in prerequisites and preparing cloud clusters for registration.
> Added that AWS-EKS is supported 

- versioned_docs/version-0.2.0/getting-started-with-kind-clusters.mdx
Fixed the indentation issue in the Kind Cluster tutorial
> Fixed the indentation issue in the Kind Cluster tutorial

- README.md
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #43
> updated the node version in readme file

- blog/2022-09-8-office-hours.mdx
Signed-off-by: 26tanishabanik <26tanishabanik@gmail.com>
Fixes #57
> added 8th sept blog for office hours

- blog/2022-09-8-office-hours.mdx
Signed-off-by: 26tanishabanik <26tanishabanik@gmail.com>
Fixes #57
> updated 8th sept blog for office hours

- docusaurus.config.js
- package.json
- yarn.lock
> fix(): Added GTM support

- versioned_docs/version-0.2.0/troubleshooting-guide.mdx
- versioned_docs/version-0.3.0/troubleshooting-guide.mdx
Added a troubleshooting issue on the helm upgrade in the troubleshooting guide.
> Added a troubleshooting issue on the helm upgrade

- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/installing-kubeslice/configuration-parameters.mdx
- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/installing-kubeslice/script-to-get-the-secrets-of-the-worker-cluster.mdx
- versioned_docs/version-0.3.0/getting-started-with-cloud-clusters/installing-kubeslice/configuration-parameters.mdx
- versioned_docs/version-0.3.0/getting-started-with-cloud-clusters/installing-kubeslice/script-to-get-the-secrets-of-the-worker-cluster.mdx
- Updated steps to get the network interface name.
- updated the script and script output.
- removed imagepull secrets for opensource
> AM-5256: Update script to get the worker secrets

- .github/workflows/spellcheck.yml
- spellcheck.yml
- wordlist.txt
This is one of the proposed way we can do, I'll make the other PR asap, once we compare we'll understand which would be best choice for the project. PR for #14
> Add check for typo correction across docs (proposal 1)

- versioned_docs/version-0.4.0/kubeslice-cli/installing-kubeslice-cli.mdx
Update the link to download the latest version 
3.0.1 -> 3.0.2
> AM-5707: update the link to download latest version

- versioned_docs/version-0.4.0/register-to-try.mdx
Added Eric's suggestions in the Register to try KubeSlice topic.
> Added Eric's suggestions in the Register to try KubeSlice topic

- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/prerequisites/prerequisites.mdx
- versioned_docs/version-0.3.0/getting-started-with-cloud-clusters/prerequisites/prerequisites.mdx
- versioned_docs/version-0.4.0/getting-started-with-cloud-clusters/prerequisites/prerequisites.mdx
https://projectcalico.docs.tigera.io/getting-started/kubernetes/managed-public-cloud/aks#install-aks-with-calico-for-network-policy
> update calico link for aks

- versioned_docs/version-0.4.0/kubeslice-cli/installing-kubeslice-cli.mdx
- versioned_docs/version-0.4.0/kubeslice-cli/kubeslice-cli-demo.mdx
- versioned_docs/version-0.4.0/kubeslice-cli/troubleshooting-guide.mdx
> AM-5785: update the steps in the demo using kubeslice-cli doc

- versioned_docs/version-0.4.0/kubeslice-cli/reference/sample-configuration-file.mdx
Change repo URL from  https://kubeslice.github.io/charts/ ->  https://kubeslice.github.io/kubeslice
> AM-5941: fix the repo URL

- src/css/custom.scss
Duplicated the PR as the original PR was merged into an old branch. 
I have added the setting by choosing the base as the master branch.
> Added the consistent first-level font-style custom css setting

- versioned_docs/version-0.5.0/getting-started-with-cloud-clusters/prerequisites/preparing-the-cloud-clusters-for-registration.mdx
Added the updated output of the helm search repo kubeslice command.
> Added the updated output of the helm search repo kubeslice command

- versioned_docs/version-0.5.0/kubeslice-cli/getting-started.mdx
- versioned_docs/version-0.5.0/kubeslice-cli/installing-kubeslice.mdx
- versioned_docs/version-0.5.0/tutorials/kubeslice-cli-demo-on-cloud-clusters.mdx
- Updated the release version.
- Revised the content, wherever applicable.
> AM-6339 Update kuebslice-cli release version

- versioned_docs/version-0.5.0/cloud-cluster-quick-start.mdx
Added a space after the figure in this topic.
> Added a space after the figure

- versioned_docs/version-0.6.0/getting-started-with-cloud-clusters/prerequisites/preparing-the-cloud-clusters-for-registration.mdx
- versioned_docs/version-0.6.0/kubeslice-cli/installing-kubeslice.mdx
- versioned_docs/version-0.6.0/release-notes/release-notes-for-kubeslice-oss-0.6.0.mdx
helm search repo kubeslice
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
kubeslice/cert-manager          v1.7.0          v1.7.0          A Helm chart for cert-manager
kubeslice/istio-base            1.16.0          1.16.0          Helm chart for deploying Istio cluster resource...
kubeslice/istio-discovery       1.16.0          1.16.0          Helm chart for istio control plane
kubeslice/kubeslice-controller  0.6.0           0.6.10          A Helm chart for kubeslice-controller
kubeslice/kubeslice-worker      0.6.0           0.17.1          A Helm chart for kubeslice-worker
> AM-6715: update command output for chart versions

- versioned_docs/version-0.6.0/features/ipam.mdx
- versioned_sidebars/version-0.6.0-sidebars.json
Added the IPAM feature description, which is already added as part of the enterprise docs.
> Added the IPAM feature description

- versioned_docs/version-0.6.0/features/ipam.mdx
Added a missing article in the description.
> Added an article

- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/installing-kubeslice/managing-namespaces.mdx
- versioned_docs/version-0.3.0/getting-started-with-cloud-clusters/installing-kubeslice/managing-namespaces.mdx
- versioned_docs/version-0.4.0/getting-started-with-cloud-clusters/installing-kubeslice/managing-namespaces.mdx
- versioned_docs/version-0.5.0/getting-started-with-cloud-clusters/installing-kubeslice/managing-namespaces.mdx
- versioned_docs/version-0.6.0/getting-started-with-cloud-clusters/installing-kubeslice/managing-namespaces.mdx
Rephrased the limitation in Service Export in all versions.
> Rephrased the limitation in Service Export

- versioned_docs/version-0.2.0/getting-started-with-cloud-clusters/installing-kubeslice/installing-the-kubeslice-controller.mdx
- versioned_docs/version-0.3.0/getting-started-with-cloud-clusters/installing-kubeslice/installing-the-kubeslice-controller.mdx
- versioned_docs/version-0.4.0/getting-started-with-cloud-clusters/installing-kubeslice/installing-the-kubeslice-controller.mdx
- versioned_docs/version-0.5.0/getting-started-with-cloud-clusters/installing-kubeslice/installing-the-kubeslice-controller.mdx
- versioned_docs/version-0.6.0/getting-started-with-cloud-clusters/installing-kubeslice/installing-the-kubeslice-controller.mdx
Fixed the note format that had several subsections part of it in all versions of the KubeSlice Controller topic.
> Fixed the note format that had several subsections part of it in the KubeSlice Controller topic

- docusaurus.config.js
- package-lock.json
- versioned_docs/version-0.7.0/monitor/controller-events.mdx
- yarn.lock
Rearranged Controller events; updated disabling events under KubeSlice-generated Controller Events.
> Rearranged Controller events; updated disabling events

- versioned_docs/version-1.0.0/install-kubeslice/kubeslice-cli/install-kubeslice-cli.mdx
- versioned_docs/version-1.0.0/playground/sandbox.mdx
- versioned_sidebars/version-1.0.0-sidebars.json
Fixed the links in the sandbox doc.
> AM-10951: Fixed the links in the sandbox doc

- docusaurus.config.js
- versioned_docs/version-1.0.0/uninstall-kubeslice/uninstall-kubeslice.mdx
- versioned_docs/version-1.1.0/uninstall-kubeslice/uninstall-kubeslice.mdx
Changed the default version to the latest version in OSS. Fixed the subheading, Deregistered Worker Clusters.
> Changed the default version to the latest version in OSS

- versioned_docs/version-1.0.0/install-kubeslice/kubeslice-cli/uninstall-kubeslice.mdx
- versioned_docs/version-1.0.0/release-notes/release-notes-for-kubeslice-oss-0.2.0.mdx
- versioned_docs/version-1.0.0/release-notes/release-notes-for-kubeslice-oss-0.3.0.mdx
- versioned_docs/version-1.0.0/release-notes/release-notes-for-kubeslice-oss-0.4.0.mdx
- versioned_docs/version-1.0.0/release-notes/release-notes-for-kubeslice-oss-0.5.0.mdx
- versioned_docs/version-1.0.0/tutorials/yaml-tutorials/test-network-connectivity.mdx
- versioned_docs/version-1.0.0/uninstall-kubeslice/uninstall-kubeslice.mdx
- versioned_docs/version-1.1.0/install-kubeslice/kubeslice-cli/uninstall-kubeslice.mdx
- versioned_docs/version-1.1.0/playground/sandbox.mdx
- versioned_docs/version-1.1.0/release-notes/release-notes-for-kubeslice-oss-0.2.0.mdx
- versioned_docs/version-1.1.0/release-notes/release-notes-for-kubeslice-oss-0.3.0.mdx
- versioned_docs/version-1.1.0/release-notes/release-notes-for-kubeslice-oss-0.4.0.mdx
- versioned_docs/version-1.1.0/release-notes/release-notes-for-kubeslice-oss-0.5.0.mdx
- versioned_docs/version-1.1.0/tutorials/yaml-tutorials/deploy-the-bookinfo-application-on-an-intra-cluster-slice.mdx
- versioned_docs/version-1.1.0/tutorials/yaml-tutorials/deploy-the-bookinfo-application.mdx
- versioned_docs/version-1.1.0/tutorials/yaml-tutorials/deploy-the-iperf-application-on-an-intra-cluster-slice.mdx
- versioned_docs/version-1.1.0/tutorials/yaml-tutorials/deploy-the-iperf-application.mdx
- versioned_docs/version-1.1.0/tutorials/yaml-tutorials/test-network-connectivity.mdx
- versioned_docs/version-1.1.0/uninstall-kubeslice/uninstall-kubeslice.mdx
Fixed the broken and incorrect links in version 1.0.0 and 1.1.0.
> Fixed the broken and incorrect links in version 1.0.0 and 1.1.0

- versioned_docs/version-1.0.0/get-started/prerequisites/prerequisites-kubeslice-cli-install.mdx
- versioned_docs/version-1.1.0/get-started/prerequisites/prerequisites-kubeslice-cli-install.mdx
Revised the steps to install the kubeslice-cli tool on Linux and macOS. 
Please review the content and provide your feedback.
> Revised the steps to install the kubeslice-cli tool on Linux and macOS

- CONTRIBUTING.md
> fix(): repo name mistake

- versioned_docs/version-1.2.0/get-started/prerequisites/prerequisites-configure-helm-repository.mdx
- versioned_docs/version-1.2.0/release-notes/release-notes-for-kubeslice-oss-1.2.1.mdx
- versioned_docs/version-1.2.0/tutorials/yaml-tutorials/deploy-the-bookinfo-application-on-an-intra-cluster-slice.mdx
- versioned_docs/version-1.2.0/tutorials/yaml-tutorials/deploy-the-bookinfo-application.mdx
- versioned_docs/version-1.2.0/tutorials/yaml-tutorials/deploy-the-iperf-application-on-an-intra-cluster-slice.mdx
- versioned_docs/version-1.2.0/tutorials/yaml-tutorials/deploy-the-iperf-application.mdx
- versioned_sidebars/version-1.2.0-sidebars.json
- Related Issue # https://github.com/kubeslice/docs/issues/164
- Closes #
> Mainline doc updates and release notes for OSS v1.2.1

- versioned_docs/version-1.0.0/tutorials/yaml-tutorials/deploy-the-iperf-application-on-an-intra-cluster-slice.mdx
- versioned_docs/version-1.0.0/tutorials/yaml-tutorials/deploy-the-iperf-application.mdx
- versioned_docs/version-1.1.0/tutorials/yaml-tutorials/deploy-the-iperf-application-on-an-intra-cluster-slice.mdx
- versioned_docs/version-1.1.0/tutorials/yaml-tutorials/deploy-the-iperf-application.mdx
- versioned_docs/version-1.2.0/tutorials/yaml-tutorials/deploy-the-iperf-application.mdx
- versioned_docs/version-1.3.0/tutorials/yaml-tutorials/deploy-the-iperf-application.mdx
Edits in the tutorial slice config YAMLs
- Related Issue #
- Closes #
> Edits in the tutorial slice config YAMLs

- versioned_docs/version-1.3.0/get-started/prerequisites/prerequisites-configure-helm-repository.mdx
- versioned_docs/version-1.3.0/release-notes/release-notes-for-kubeslice-oss-1.3.1-cli.mdx
- versioned_docs/version-1.3.0/release-notes/release-notes-for-kubeslice-oss-1.3.1.mdx
- versioned_sidebars/version-1.3.0-sidebars.json
Added release notes and updated chart versions for OSS v1.3.1
- Related Issue # https://github.com/kubeslice/docs/issues/180
- Closes # https://github.com/kubeslice/docs/issues/180
> Added release notes and updated chart versions for OSS v1.3.1

- versioned_docs/version-1.3.0/tutorials/kubeslice-cli-tutorials/kubeslice-cli-demo.mdx
> fix the wrong cluster name

- versioned_docs/version-1.3.0/overview/architecture.mdx
Updated the KubeSlice architecture description
- Related Issue # https://github.com/kubeslice/docs/issues/184
- Closes # https://github.com/kubeslice/docs/issues/184
> Updated the KubeSlice architecture description

- versioned_docs/version-1.3.0/overview/overview.mdx
Replaced the content of What is KubeSlice with the cont3ent that Prabhu shared. 
- Related Issue # https://github.com/kubeslice/docs/issues/191
- Closes # https://github.com/kubeslice/docs/issues/191
> Replaced the content of What is KubeSlice

- versioned_docs/version-1.3.0/use-cases/mongodb/distributed-mongodb-for-multicloud.mdx
> fixed a broken link

- versioned_docs/version-1.4.0/install-kubeslice/yaml/yaml-register-worker-clusters.mdx
> updated the doc
